//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoopVariants.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoopVariants.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Gold_texRampCaptainAirstrike {
            get {
                object obj = ResourceManager.GetObject("Gold_texRampCaptainAirstrike", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Gold_texRampMagmaWorm {
            get {
                object obj = ResourceManager.GetObject("Gold_texRampMagmaWorm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Gold_texSPGroundRed {
            get {
                object obj = ResourceManager.GetObject("Gold_texSPGroundRed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Material_2_Color {
            get {
                object obj = ResourceManager.GetObject("Material_2_Color", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] RJDistantTreeFoliage_Color {
            get {
                object obj = ResourceManager.GetObject("RJDistantTreeFoliage_Color", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] RJDistantTreeFoliageCard {
            get {
                object obj = ResourceManager.GetObject("RJDistantTreeFoliageCard", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] RJfern_Billboard_Color {
            get {
                object obj = ResourceManager.GetObject("RJfern_Billboard_Color", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] RJfern_Color {
            get {
                object obj = ResourceManager.GetObject("RJfern_Color", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] RJHangingMoss_Color {
            get {
                object obj = ResourceManager.GetObject("RJHangingMoss_Color", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] RJMossFoliage_Billboard_Color {
            get {
                object obj = ResourceManager.GetObject("RJMossFoliage_Billboard_Color", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] RJMossFoliage_Color {
            get {
                object obj = ResourceManager.GetObject("RJMossFoliage_Color", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] RJpinkshroom_Billboard_Color {
            get {
                object obj = ResourceManager.GetObject("RJpinkshroom_Billboard_Color", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] RJpinkshroom_Color {
            get {
                object obj = ResourceManager.GetObject("RJpinkshroom_Color", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] RJShroomFoliage_Billboard_Color {
            get {
                object obj = ResourceManager.GetObject("RJShroomFoliage_Billboard_Color", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] RJShroomFoliage_Color {
            get {
                object obj = ResourceManager.GetObject("RJShroomFoliage_Color", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] RJTowerTreeBark {
            get {
                object obj = ResourceManager.GetObject("RJTowerTreeBark", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] RJTowerTreeFoliage {
            get {
                object obj = ResourceManager.GetObject("RJTowerTreeFoliage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] RJTowerTreeFoliage_Billboard_Color {
            get {
                object obj = ResourceManager.GetObject("RJTowerTreeFoliage_Billboard_Color", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] RJTowerTreeFoliage_Color {
            get {
                object obj = ResourceManager.GetObject("RJTowerTreeFoliage_Color", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] RJTreeBigFoliage_Billboard_Color {
            get {
                object obj = ResourceManager.GetObject("RJTreeBigFoliage_Billboard_Color", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] RJTreeBigFoliage_Color {
            get {
                object obj = ResourceManager.GetObject("RJTreeBigFoliage_Color", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] spmDCFern1_Atlas {
            get {
                object obj = ResourceManager.GetObject("spmDCFern1_Atlas", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] spmRJgrass1_Billboard_Color {
            get {
                object obj = ResourceManager.GetObject("spmRJgrass1_Billboard_Color", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] spmRJgrass1_Billboard_Subsurface {
            get {
                object obj = ResourceManager.GetObject("spmRJgrass1_Billboard_Subsurface", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] spmRJgrass1_Color {
            get {
                object obj = ResourceManager.GetObject("spmRJgrass1_Color", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] spmRJgrass1_Subsurface {
            get {
                object obj = ResourceManager.GetObject("spmRJgrass1_Subsurface", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] spmRJgrass2_Billboard_Color {
            get {
                object obj = ResourceManager.GetObject("spmRJgrass2_Billboard_Color", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] spmRJgrass2_Billboard_Subsurface {
            get {
                object obj = ResourceManager.GetObject("spmRJgrass2_Billboard_Subsurface", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] spmRJgrass2_Color {
            get {
                object obj = ResourceManager.GetObject("spmRJgrass2_Color", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] spmRJgrass2_Subsurface {
            get {
                object obj = ResourceManager.GetObject("spmRJgrass2_Subsurface", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] spmRJgrasstest_Billboard_Color {
            get {
                object obj = ResourceManager.GetObject("spmRJgrasstest_Billboard_Color", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] spmRJgrasstest_Color {
            get {
                object obj = ResourceManager.GetObject("spmRJgrasstest_Color", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] spmSPVine {
            get {
                object obj = ResourceManager.GetObject("spmSPVine", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texDCGrass {
            get {
                object obj = ResourceManager.GetObject("texDCGrass", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texDCGravelDiffuse {
            get {
                object obj = ResourceManager.GetObject("texDCGravelDiffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texDCRockSide {
            get {
                object obj = ResourceManager.GetObject("texDCRockSide", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texHRLavaDiffuse {
            get {
                object obj = ResourceManager.GetObject("texHRLavaDiffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texHRLavaDiffuse_opt {
            get {
                object obj = ResourceManager.GetObject("texHRLavaDiffuse_opt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texMalachite {
            get {
                object obj = ResourceManager.GetObject("texMalachite", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampArtifactShellSoft {
            get {
                object obj = ResourceManager.GetObject("texRampArtifactShellSoft", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampCaptainAirstrike {
            get {
                object obj = ResourceManager.GetObject("texRampCaptainAirstrike", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampGreaterWisp {
            get {
                object obj = ResourceManager.GetObject("texRampGreaterWisp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampMagmaWorm {
            get {
                object obj = ResourceManager.GetObject("texRampMagmaWorm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampRJMushroom {
            get {
                object obj = ResourceManager.GetObject("texRampRJMushroom", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampTeleporterSoft {
            get {
                object obj = ResourceManager.GetObject("texRampTeleporterSoft", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRJDirtDiffuse {
            get {
                object obj = ResourceManager.GetObject("texRJDirtDiffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRJGrassTerrain {
            get {
                object obj = ResourceManager.GetObject("texRJGrassTerrain", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRJGrassTerrain2 {
            get {
                object obj = ResourceManager.GetObject("texRJGrassTerrain2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRJLichenTerrain {
            get {
                object obj = ResourceManager.GetObject("texRJLichenTerrain", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRJMoss {
            get {
                object obj = ResourceManager.GetObject("texRJMoss", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRJMossPatch1Diffuse {
            get {
                object obj = ResourceManager.GetObject("texRJMossPatch1Diffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRJMossPatch2Diffuse {
            get {
                object obj = ResourceManager.GetObject("texRJMossPatch2Diffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRJMossPatchLargeDiffuse {
            get {
                object obj = ResourceManager.GetObject("texRJMossPatchLargeDiffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRJpinkshroomEmission {
            get {
                object obj = ResourceManager.GetObject("texRJpinkshroomEmission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRJShroomBigDiffuse {
            get {
                object obj = ResourceManager.GetObject("texRJShroomBigDiffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRJShroomBigEmissive {
            get {
                object obj = ResourceManager.GetObject("texRJShroomBigEmissive", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRJShroomBounceDiffuse {
            get {
                object obj = ResourceManager.GetObject("texRJShroomBounceDiffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRJShroomShelfDiffuse {
            get {
                object obj = ResourceManager.GetObject("texRJShroomShelfDiffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRJShroomShelfEmissive {
            get {
                object obj = ResourceManager.GetObject("texRJShroomShelfEmissive", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRJShroomSmallDiffuse {
            get {
                object obj = ResourceManager.GetObject("texRJShroomSmallDiffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRJShroomSmallEmissive {
            get {
                object obj = ResourceManager.GetObject("texRJShroomSmallEmissive", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRJTree {
            get {
                object obj = ResourceManager.GetObject("texRJTree", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRJTreeTop {
            get {
                object obj = ResourceManager.GetObject("texRJTreeTop", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRJTriangleDiffuse {
            get {
                object obj = ResourceManager.GetObject("texRJTriangleDiffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texSkyboxSP {
            get {
                object obj = ResourceManager.GetObject("texSkyboxSP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texSPCoralEmi {
            get {
                object obj = ResourceManager.GetObject("texSPCoralEmi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texSPCoralString {
            get {
                object obj = ResourceManager.GetObject("texSPCoralString", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texSPGrass {
            get {
                object obj = ResourceManager.GetObject("texSPGrass", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texSPGrassEMI {
            get {
                object obj = ResourceManager.GetObject("texSPGrassEMI", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texSPGroundDIFMain {
            get {
                object obj = ResourceManager.GetObject("texSPGroundDIFMain", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texSPGroundDIFPale {
            get {
                object obj = ResourceManager.GetObject("texSPGroundDIFPale", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texSPGroundDIFVein {
            get {
                object obj = ResourceManager.GetObject("texSPGroundDIFVein", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texSPGroundRed {
            get {
                object obj = ResourceManager.GetObject("texSPGroundRed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texSPGroundRed_FORLAVA {
            get {
                object obj = ResourceManager.GetObject("texSPGroundRed_FORLAVA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texSPSpheremoss {
            get {
                object obj = ResourceManager.GetObject("texSPSpheremoss", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texSPSphereRock {
            get {
                object obj = ResourceManager.GetObject("texSPSphereRock", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texSPTallGrass {
            get {
                object obj = ResourceManager.GetObject("texSPTallGrass", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texWhiteSandSimple {
            get {
                object obj = ResourceManager.GetObject("texWhiteSandSimple", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] VeinEM {
            get {
                object obj = ResourceManager.GetObject("VeinEM", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
